openshift/network-tools

Dockerfile
The previous image is only accessible within CI, so making changes
to test things is tricky.
=> Switch to centos 8 for upstream changes

README.md
=> Fix README broken link and give a clearer explanation of debug scripts

debug-scripts/pod_to_svc.sh
/assign @rcarrillocruz 
cc @fbac @palonsoro
=> Initial implementation of pod to svc test.

Dockerfile, Dockerfile.rhel7, Makefile, debug-scripts/ovn/pod_to_pod.sh
**What is the aim of the script?**
Test connectivity between pods in OVN. It runs ovnkube-trace between the pods in case of connectivity failure to check what went wrong.
**How to test the script?**
The script assumes that $KUBECONFIG file is loaded/mounted at `/tmp/kubeconfig` inside the pod. This is just temporary and will go away once we add a serviceaccount for the debug-namespace.
Method 1: Launch a debug pod on an OCP OVN cluster:
Sample yaml:
```
---
apiVersion: v1
kind: Pod
metadata:
name: pod1
labels:
app: MyApp
spec:
containers:
- name: pod1
image: quay.io/itssurya/dev-images:5919d6a1-080e-4bb2-a8b5-62627c78b2c7
command:
- /sbin/init
```
Replace the image with `registry.svc.ci.openshift.org/ocp/4.7:ocp-debug-network` once the image lands in the registry.
`oc rsh -n …
=> SDN-1334: Pod to pod connectivity for OVN

Dockerfile, Dockerfile.rhel7, debug-scripts/ovn/pod_to_pod.sh, debug-scripts/ovn/pod_to_svc.sh
**What is the aim of the script?**
Test connectivity between pod and svc in OVN. It runs ovnkube-trace between the pod and svc in case of connectivity failure to check what went wrong.
**How to test the script?**
The script assumes that $KUBECONFIG file is loaded/mounted at /tmp/kubeconfig inside the pod. This is just temporary and will go away once we add a serviceaccount for the debug-namespace.
Method 1: Launch a debug pod on an OCP OVN cluster:
Sample yaml:
```
---
apiVersion: v1
kind: Pod
metadata:
name: pod1
labels:
app: MyApp
spec:
containers:
- name: pod1
image: quay.io/itssurya/dev-images:15084af4-4491-44a2-94bf-c62bfdeb7131
command:
- /sbin/init
```
Replace the image with `registry.svc.ci.openshift.org/ocp/4.7:ocp-debug-network` once the image lands in the registry.
`oc rsh -n …
=> SDN-1334: Pod to svc connectivity check in OVN

Dockerfile, Dockerfile.fedora, Dockerfile.rhel7, Makefile
This patch also moves the installation of ovnkube-trace to the Dockerfile so that it is available in the image directly instead of having to install it in each script.
Users can invoke ovnkube-trace using:
```
oc adm network-tools -- ovnkube-trace --tcp --src <src-pod-name> --dst <dst-pod-name> --loglevel=5
```
once we integrate this image with oc client (this is WIP right now).
Note: I haven't changed the centos DockerFile to be based on openshift-tools. I think we can keep that image as testing image and have some level of freedom there.
/assign @rcarrillocruz
=> SDN-1492: Base network-tools on top of openshift-tools

Dockerfile
`git clone` is not allowed for images according to ART.
This patch grabs it directly from ovn-k8s image.
Depends-on: https://github.com/openshift/ovn-kubernetes/pull/416
=> SDN-1492: Fix art build failure

README.md, docs/contributor.md, docs/user.md
- Contributor docs: Adds a minimum set of instructions for writing scripts
-  User docs: Maintain information about each script.
Note that the user-docs need to be updated once we get the oc adm network-tools patch in. The initial documentation is being pushed to satisfy the security review.
=> SDN-1567: Add User and Contributor Docs

debug-scripts/common
As the title suggests, during the development stages, personal quay images were used. Now that network-tools is public on quay we can fix this in the code base.
=> Replace the image with the official openshift quay one

debug-scripts/sdn_cluster_and_node_info
Make the base folder `network-tools` under which all logs can go under. Hence when using must-gather, one can specify the --src-dir from where the logs need to be copied from.
=> Bug 1967933: Add proper directory path to which output will be saved

debug-scripts/gather, debug-scripts/network-tools, docs/contributor.md, docs/user.md
This PR adds a gather script, that in turn calls the network-tools script. This is to maintain compatibility with must-gather tooling since the script entrypoint must be named as `gather`
=> Bug 1967933: Add entry point for must-gather tooling

debug-scripts/ovn_ipsec_connectivity, debug-scripts/ovn_nic_firmware, debug-scripts/ovn_pod_to_pod_connectivity, debug-scripts/ovn_pod_to_svc_connectivity, debug-scripts/sdn_cluster_and_node_info, debug-scripts/sdn_node_connectivity, debug-scripts/sdn_pod_to_pod_connectivity, debug-scripts/sdn_pod_to_svc_connectivity, docs/contributor.md
Adding provision to download logs from each script in addition to std-outing. This is to maintain compatibility with must-gather way of things.
=> Bug 1967933: Save logs to file as well in addition to stdouting

debug-scripts/ovn_cleanConntrack
Script to detect persistent conntrack lines that should have been removed (BZ [2043094])
For testing purposes a fake conntrack line based in our cluster networks can be inserted:
```
sh-4.4# conntrack -I -p udp -s 10.130.1.44 -d 172.30.2.3 --sport 3333 --dport 60003 -t 60                                                                    
conntrack v1.4.4 (conntrack-tools): 1 flow entries have been created.
sh-4.4# exit
exit
#Generating lines for node (rna1-master-2.rna1.cloud.lab.eng.bos.redhat.com) subnet:10.128.2.0                                                               
#Raw line:udp 17 52 src=10.130.1.44 dst=172.30.2.3 sport=3333 dport=60003 src=172.30.2.3 dst=10.130.1.44 sport=60003 dport=3333 mark=0 secctx=system_u:object_r:unlabeled_t:s0 use=1
conntrack -D -s 10.130.1.44 -d …
```
=> Bug 2043094: Add ovn clean conntrack functionality

debug-scripts/local-scripts/ci-artifacts-get, debug-scripts/local-scripts/local-scripts-map, debug-scripts/local-scripts/ovn-pprof-forwarding, debug-scripts/network-tools, debug-scripts/scripts/ovn-metrics-list, docs/contributor.md, docs/generate-docs, docs/user.md
Improve network-tools help: add sections for better readability.
Add 1 common script:
- ovn-metrics-list to collect ovn networking metrics: master, node,
and ovn
Add 2 local scripts:
- ci-artifacts-get to Download ci prow job artifacts
- ovn-pprof-forwarding to Make ovn pprof endpoints available on
localhost
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
=> Migrate existing scripts to network-tools

debug-scripts/local-scripts/ovn-pprof-forwarding, debug-scripts/network-tools, debug-scripts/scripts/ovn-db-run-command, debug-scripts/scripts/ovn-get, debug-scripts/test-networking/main, debug-scripts/utils, docs/user.md
Add common scripts:
- ovn-db-run-command to run ovndb command like "ovn-nbctl" inside a
leader pod
- ovn-get to get/download ovn information from the cluster
Depends on https://github.com/openshift/network-tools/pull/65 (merged)
=> Implement new scripts to interact with ovn cluster

debug-scripts/network-tools, debug-scripts/scripts/pod-run-netns-command, debug-scripts/utils, docs/user.md
container within existing pod netnamespace.
This command has multiple options and examples, please check
if they all make sense and work properly.
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
=> Add pod-run-netns-command script to run command from network-tools

README.md, debug-scripts/local-scripts/ovn-db-run-locally, debug-scripts/utils
Use get_full_path for file inputs to make sure we convert relative path correctly.
Only use bash -c with braced commands for netnamespace
Add contacts in README
Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>
=> Minor fixed found during demo preparation

OWNERS
Though network-tools doesn't have a subcomponent, it still should be assigned one to have bugs successfully come into the networking/subcomponent.
Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
=> Rename subcomponent to ensure bugs are assigned correctly

debug-scripts/utils
Starting in Kubernetes v1.26, OVN-Kubernetes uses the lease API to publish the leader identity. 
To keep backwards compatibility fallback to a configmap.
Signed-off-by: Patryk Diak <pdiak@redhat.com>
=> OCPBUGS-7106: Get OVN-Kubernetes leader identity from the lease

Dockerfile
It's inconsistent that the base image is RHEL8 but that it also copies ovnkube-trace from the RHEL9-based ovn-kubernetes image. The two images should use the same base (eg, RHEL9).
=> Dockerfile: move to RHEL9 base image

debug-scripts/local-scripts/ovn-db-run-locally
This commit improves the checking of the dbs that are not clustered. When db is not clustered, the check actually returned a failure, which would cause the script failure to be caught and cause the container to exit. Then, the user would never make it to the bash prompt.
=> ovn-db-run-locally: gracefully handle non-clustered dbs

jira-scripts/.gitignore, jira-scripts/README.md, jira-scripts/network_bugs_overview, jira-scripts/requirements.txt, jira-scripts/single_query
Migrating jira (and bugzilla) query scripts from
https://github.com/dougsland/bz-query to network-tools/jira-scripts. And tweaking README.md to reflect its new home.
Reported-at: https://issues.redhat.com/browse/SDN-4047
=> SDN-4047: Migrate bug-dispath query scripts

debug-scripts/local-scripts/ovn-pprof-forwarding, debug-scripts/scripts/ovn-db-run-command, debug-scripts/scripts/ovn-get, debug-scripts/scripts/ovn-metrics-list, debug-scripts/utils, docs/user.md
Support scripts on network-tools side on IC mode.
TODO: 
Reported-at: https://issues.redhat.com/browse/SDN-3904
Slides 74+ in https://docs.google.com/presentation/d/1HXhY0cK5wiO-xRrbKdATpZ3xRCQPXJy_WRY-Ys9IjcM/edit?usp=sharing
```
$ network-tools ovn-get mode
cluster is running in multi-zone (ovn-interconnect / ovn-ic)
```
On non ovn-ic cluster, you will see:
```
$ network-tools ovn-get mode
cluster is running in single-zone (legacy)
```
```
$ network-tools ovn-get leaders
ovn-k master leader ovnkube-control-plane-XYZ
nbdb leader not applicable in ovn-ic mode
sbdb leader not applicable in ovn-ic mode
```
With ovn-ic, the ovn dbs are present on every ovnkube-node pod.
That is fundamentally different from previous releases, where ovn dbs would be in the master pods.
-- 
```
$ network-tools …
```
=> SDN-3904: Update scripts in network-tools to reflect the changes in IC model

README.md, debug-scripts/scripts/ovn-db-run-command, debug-scripts/scripts/ovn-get, debug-scripts/scripts/ovn-metrics-list, debug-scripts/scripts/pod-run-netns-command, debug-scripts/test-networking/main, debug-scripts/test-networking/ovn_ipsec_connectivity, debug-scripts/test-networking/ovn_nic_firmware, debug-scripts/test-networking/ovn_pod_to_pod_connectivity, debug-scripts/test-networking/ovn_pod_to_svc_connectivity, debug-scripts/test-networking/sdn_cluster_and_node_info, debug-scripts/test-networking/sdn_node_connectivity, debug-scripts/test-networking/sdn_pod_to_pod_connectivity, debug-scripts/test-networking/sdn_pod_to_svc_connectivity, debug-scripts/utils, docs/user.md
Since https://github.com/openshift/cluster-samples-operator/pull/495 we have image stream for network-tools, so we should use it instead of quay image. It exists for 4.13+ clusters
=> Update docs to use image-streams instead of quay image

debug-scripts/local-scripts/ovn-pprof-forwarding
Before you got errors from commands trying to figure out ovn mode
```
network-tools -h
error: You must be logged in to the server (Unauthorized)
error: You must be logged in to the server (Unauthorized)
Usage: network-tools [command]
```
=> OCPBUGS-22166: Move commands to the function to avoid them being executed on -h.

jira-scripts/README.md, jira-scripts/network_bugs_overview
A long-due cleanup of our script and a new functionality to create jira stories for each ovnk upstream issue labeld with `ci-flake`.
To sum up the relevant input parameters:
-  `./network_bugs_overview -g` retrieves ovnk upstream issues and tracks them inside the [SDN-4175](https://issues.redhat.com//browse/SDN-4175) epic; assignees are kept whenever possible. For instance:
```
$ ./network_bugs_overview -g
- Found 18 github issues with ci-flake label
- Found 17 bugs in 1.4s with the query: project = SDN AND "Epic Link" = SDN-4175 AND Summary ~ "upstream-*"
Created the following JIRA stories:
https://issues.redhat.com/browse/SDN-4213
WARNING: the status following jira stories doesn't match the status of their corresponding github issue:
https://issues.redhat.com/browse/SDN-4205
```
- …
=> SDN-4182: Script cleanup + track ovnk upstream issues in jira

debug-scripts/network-tools, debug-scripts/scripts/ovn-count-flows, debug-scripts/utils, docs/user.md
Required to investigate ACLs (network policy) impact in the OVS flows number.
Expected output:
```
$ network-tools ovn-count-flows -l 10 ovnkube-node-6pnpv
Leader pod is ovnkube-master-t679l
NOTE: Every ACL will likely be printed twice, that is expected and means that the number of OVS flows for a given ACL is a sum of all entries with the same name+ids
Number of OVS flows=12 for ACL with name and ids = clusterPortGroup_DefaultDenyMulticastEgress {default-deny-policy-type=Egress}
Number of OVS flows=12 for ACL with name and ids = clusterRtrPortGroup_DefaultAllowMulticastEgress {default-deny-policy-type=Egress}
Number of OVS flows=12 for ACL with name and ids = clusterRtrPortGroup_DefaultAllowMulticastIngress {default-deny-policy-type=Ingress}
Number of OVS flows=12 for ACL with name and …
```
=> SDN-4189: Add flow counter script for ACLs

jira-scripts/network_bugs_overview
**Align status and assignee between jira and github**
Github is the source of truth:
- For a given github issue, the jira story that tracks it must show the same status (open / closed) and the same assignee; if not, script will align it. 
- If ever more than one jira story tracks the same github issue, then the jira story with the lowest ID is kept and all other ones are closed.
=> OCPBUGS-24385: Align status and assignee between jira and github

debug-scripts/scripts/ovn-count-flows
When logical flows are translated to OVS flows, first 8 chars of logical_flow UUID are used as a cookie, but leading zeros are dropped. To create a valid sbdb request, restore missing zeros knowing we expect is to be 8 chars.
=> SDN-4189: Update OVS flows counter to work for cookies with leading 0.

debug-scripts/network-tools, debug-scripts/scripts/ovn-perf-scanner
(Unreasonably long poll intervals, but not only). It may be used to analyse a live cluster or a must-gather to find disturbing signs of OVN overload that are logged as WARNING messages.
=> SDN-4194: Add a script to find OVN perf problems

jira-scripts/network_bugs_overview
- Only consider bugs in new, assigned, post state in the bug count
- Remove SAST,ART,backport bugs from bug count & show them separately
=> NO-JIRA: Remove SAST,ART,backport bugs from bug count & show them separately

jira-scripts/network_bugs_overview
* Simplify user name handling when reading and creating jira stories
* Add a total line to the bug ranking output
* Support pagination when retrieving github issues
* Clean team member list and add tim
* Separate backports from scan bugs
* Show bugs owned by developers not in our team (external)
```
Rank of developers least overloaded (today) [2024-02-07]:
========================================================
---  -------------------  --------  ------  -----  ----------  ------  -----------  ----------  -------
1  bpickard@redhat.com        10       1      1           0       0            0           4        5
2    trozet@redhat.com       100       1      0           0       1            0           0        1
3  jcaamano@redhat.com       210       3      1           2       0 …
```
=> NO-JIRA: add total and external rows + misc fixes

jira-scripts/network_bugs_overview
Example output:
```
$ ./network_bugs_overview -vq
- Found 118 bugs in 8.8s with the query: project=OCPBUGS and component in ("networking", "networking / openshift-sdn", "networking / ovn-kubernetes", "networking / cloud-network-config-controller", "networking / ingress-node-firewall", "networking / cluster-network-operator", "networking / network-tools") and status in ("NEW", "ASSIGNED", "POST", "ON_DEV")
- Found 13 bugs in 1.7s with the query: project = SDN AND "Epic Link" = SDN-4175 AND Summary ~ "upstream-*" AND filter in (Unresolved) AND assignee != "bbennett@redhat.com" AND assignee is not EMPTY
Rank of developers least overloaded (today) [2024-02-07]:
========================================================
#1 Developer: bpickard@redhat.com
Rank Points: 210
Bugs:        3
OVN-K …
```
=> NO-JIRA:Fix bug list formatting in verbose mode and remove metal lb component

Dockerfile, Dockerfile.fedora, docs/user.md
wireshark was added here https://github.com/openshift/network-tools/pull/20 and only needs `tshark` to work.
=> OCPBUGS-31699: replace wireshark with wireshark-cli

jira-scripts/network_bugs_overview
This PR adds the "PX Impact Score" to the output for --new-bugs to the ./network_bugs_overview script. PX Impact Score is from the "Product Experience" tab in OCPBUGS and is a numeric "severity" that is calculated by an algorithm described here: [PX Prioritization Algorithm Details](https://spaces.redhat.com/pages/viewpage.action?spaceKey=PPE&title=PX+Prioritization+Algorithm+Details)
Basically, every bugs starts out with a score of 6000. There are 4 factors that can increase the score up to 12000:
- The total quantity of linked cases
- The quantity of linked cases with a specific severity
- The "complexity" and quantity of the linked cases
- PX properties like "Impact range" and "technical impact" set manually by me (or anyone)
I'd like to get Px Impact Score into the output for new bugs …
=> NO-JIRA: Px score for bugs

debug-scripts/test-networking/common, debug-scripts/utils
The containerRuntime changed from runc to crun from 4.18, so we need to update network-tools utils.
/cc @npinaeva 
PTAL, thanks so much ^ ^
=> OCPBUGS-45318: change containerRuntime from runc to crun

vendor/github.com/openshift/build-machinery-go/go.mod, vendor/modules.txt
Image build for network-tools on 4.16 was failing on Konflux due to missing go mod dependencies.
```
2025-03-25 21:08:20,106 ERROR vendor/modules.txt changed after vendoring:
diff --git a/vendor/modules.txt b/vendor/modules.txt
index 11b55ac..ca0e58f 100644
--- a/vendor/modules.txt
+++ b/vendor/modules.txt
@@ -1,5 +1,5 @@
-## explicit
+## explicit; go 1.13
github.com/openshift/build-machinery-go
github.com/openshift/build-machinery-go/make
github.com/openshift/build-machinery-go/make/lib
2025-03-25 21:08:20,130 ERROR PackageRejected: The content of the vendor directory is not consistent with go.mod.
```
=> [ART-11792]  add missing go vendors

jira-scripts/network_bugs_overview
- We migrated our jira project from SDN to CORENET
- Somehow the filter "filter in (Unresolved)" is broken now, along with others that we use: https://issues.redhat.com/secure/ManageRichFilters.jspa#/2201/static  . Let's fix that with "resolution = Unresolved".
Note: the full query we use to retrieve unassigned bugs still has references to SDN filters for what concerns upstream issues tracked in our jira project. In order to fix that, I'll need to create new filters on jira first and once that is done I will open a separate PR.
=> NO-JIRA: Fix JIRA queries

jira-scripts/network_bugs_overview
.. for the last 5 days..
The problem I am trying to solve is that there is
not enough resources to manage the bugs on the bot, so we need some tooling to help.
This helps give our networking consumers confidence we are listening and importantly reacting to their updates.
New tool idea in future might also print bugs with severity or priorty change.
Tool will print out bugs that have new comments within the last 4 days with a URL you can click on.
- Found 109 bugs in 20.8s with the query: assignee = "sdn-team-bot@redhat.com" AND type = Bug AND resolution = Unresolved
Checking 109 bug issues assigned to 'sdn-team-bot' for recent comments...
======================================================================
🐛 When mutlicast traffic reaches br-ex OVS bridge is flooding the network causing …
=> NO-JIRA: add tooling to reduce bug backlog toil for viewing bz comment updates
